### ISSUE TITLE
Having trouble to make valid "response" for MC7455 modem

### ISSUE THREAD

**Issue by amore-amore** [bkerler/SierraWirelessGen#1] opened 2018-07-26 14:56 UTC
I've tried to make acceptable "response" for MC7455 modem. All the codes (generated with different modes V2, V3, V4, or V5) return ERROR.  I'm using 'Releasex64.zip' binary to make responses.

AT!OPENLOCK?
modem returns CODEXXXXXXX
tried both without quotes and with it
AT!OPENLOCK=XXXXXXXXXXXXXXXX
AT!OPENLOCK="XXXXXXXXXXXXXXXX"
with no luck.

ATI returns
Manufacturer: Sierra Wireless, Incorporated
Model: MC7455
Revision: SWI9X30C_02.08.02.00 r5428 CARMD-EV-FRMWR2 2016/01/06 20:38:53
....

What I'm doing wrong or can it be a bug?

**Comment by bkerler** [comment] 2018-08-01 18:02
You are most probably doing nothing wrong and this isn't a bug. It just means that your firmware uses a different crypto scheme.

**Comment by amore-amore** [comment] 2018-08-04 09:31
What exact MC7455 firmware version can be unlocked using this calc?

**Comment by bkerler** [comment] 2018-08-20 11:25
Issue is hopefully fixed with dcb2ee9

**Comment by HeavyDutySoul** [comment] 2018-09-03 13:00
It still doesn't work... :(

**Comment by bkerler** [comment] 2019-04-21 08:57
Duplicate of #2

**Closed by bkerler** 2019-04-21 08:57 UTC
Labels: bug
